/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type PartnersRegistryContractFunctions1 =
  | []
  | [PartnersRegistryContractFunctions]
  | [PartnersRegistryContractFunctions, PartnersRegistryContractEvents];
export type SWEvent = {
  event: PartnersRegistryContractEventType;
  args: any;
}[];

export interface PartnersRegistryContractFunctions {
  agreementIds: () => Promise<number>;
  agreements: () => Promise<string>;
  create: (
    communityAddress: string,
    rolesCount: number,
    commitmentLevel: number,
    partnersContractAddress: string
  ) => Promise<{wait: () => Promise<PartnersRegistryContractEvents>}>;
  deployer: () => Promise<string>;
  getPartnerAgreementAddresses: () => Promise<string[]>;
  initialize: (
    _skillWalletAddress: string,
    _interactionNFTFactory: string
  ) => Promise<{wait: () => Promise<PartnersRegistryContractEvents>}>;
  interactionNFTFactory: () => Promise<string>;
  migrate: (_agreement: string) => Promise<{wait: () => Promise<PartnersRegistryContractEvents>}>;
  setVersion: (_version: number) => Promise<{wait: () => Promise<PartnersRegistryContractEvents>}>;
  skillWalletAddress: () => Promise<string>;
  version: () => Promise<number>;
}
export interface PartnersRegistryContractEvents {
  events: SWEvent;
}

export enum PartnersRegistryContractEventType {
  PartnersAgreementCreated = "PartnersAgreementCreated"
}
