import { CallOverrides } from "ethers";
      /* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CommunityRegistryContractFunctions1 =
  | []
  | [CommunityRegistryContractFunctions]
  | [CommunityRegistryContractFunctions, CommunityRegistryContractEvents];
export type SWEvent = {
  event: CommunityRegistryContractEventType;
  args: any;
}[];

export interface CommunityRegistryContractFunctions {
  autIDAddr: (overrides?: CallOverrides) => Promise<string>;
  communities: (argument_0: number, overrides?: CallOverrides) => Promise<string>;
  createCommunity: (
    contractType: number,
    daoAddr: string,
    market: number,
    metadata: string,
    commitment: number,
    overrides?: CallOverrides
  ) => Promise<{wait: () => Promise<CommunityRegistryContractEvents>}>;
  getCommunities: (overrides?: CallOverrides) => Promise<string[]>;
  membershipTypes: (overrides?: CallOverrides) => Promise<string>;
  numOfCommunities: (overrides?: CallOverrides) => Promise<number>;
}
export interface CommunityRegistryContractEvents {
  events: SWEvent;
}

export enum CommunityRegistryContractEventType {
  CommunityCreated = "CommunityCreated"
}
